dist: trusty
language: node_js
- stable
script:
- npm run coverage
after_success:
- npm run publish-coverage
branches:
only: development
notifications:
  email:
    recipients:
    877385836@qq.com      # change to your own address
    20082247@mail.wit.ie    # uae other (optional)
    on_success: never        # default: change
    on_failure: always       # default: always
